export const actionCard: string
export const actionStack: string
export const approved: string
export const badge: string
export const button: string
export const buttonDefault: string
export const buttonDestructive: string
export const buttonGhost: string
export const buttonIcon: string
export const buttonPrimary: string
export const buttonSecondary: string
export const buttonSmall: string
export const card: string
export const centerCard: string
export const detailGrid: string
export const detailTopbar: string
export const empty: string
export const error: string
export const eyebrow: string
export const header: string
export const interview_completed: string
export const interview_sent: string
export const linkButton: string
export const links: string
export const longText: string
export const meta: string
export const metrics: string
export const muted: string
export const on_hold: string
export const openLabel: string
export const profileCard: string
export const queueCard: string
export const rejected: string
export const search: string
export const sectionCard: string
export const shell: string
export const spin: string
export const srOnly: string
export const submitted: string
export const table: string
export const tableHead: string
export const tableRow: string
export const timeline: string
export const timelineDot: string
export const toolbar: string
export const under_review: string
export const withdrawn: string
